apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-boot-db-volume-claim
  namespace: spring-boot-dev
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
