apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-boot-db-volume
  namespace: spring-boot-dev
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  hostPath:
    path: "G:/finki/Web/kiii/K8s/db-data"